name: Sphinx Code Documentation GitHub Pages Deploy Action
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install dependencies
        run: |
          make install
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: |
            make install-dev
            sphinx-quickstart docs --sep --no-batchfile --project chmncc --author "Eleonora Giunchiglia, Thomas Lukasiewicz, Samuele Bortolotti"  -r 0.1  --language en --extensions sphinx.ext.autodoc --extensions sphinx.ext.napoleon --extensions sphinx.ext.viewcode --extensions myst_parser
            sed -i -e "s/html_theme = 'alabaster'/html_theme = 'sphinx_rtd_theme'/g" docs/source/conf.py
            ls .
            ls ..
            sphinx-apidoc -P -o docs/source ..
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/build/html/
